### ISSUE TITLE
does it work? yes. in mumble 1.4 only

### ISSUE THREAD

**Issue by alifeee** [alifeee/Factorio-Proximity-Voice-Chat#10]
Test the mod with another player in-game

**Comment by alifeee** [comment]
no.

Mumble provides some PA settings.

The defaults are (volume changes from 1m to 15m, to a minimum of 25% volume)

![image](https://github.com/alifeee/Factorio-Proximity-Voice-Chat/assets/13833017/16f1fb2d-e1ae-4c7d-b050-1f9ecfeb5f0c)

After changing them to this (volume changes from 0m to 14.2m, to a minimum of 0% volume)

![image](https://github.com/alifeee/Factorio-Proximity-Voice-Chat/assets/13833017/f42a7571-feb3-4024-9021-1d9d30e1d9f0)

I observe:

## With only player position and camera position changing

![image](https://github.com/alifeee/Factorio-Proximity-Voice-Chat/assets/13833017/b662139c-d3cc-483a-8481-d28b05e49799)

1. When PA (Positional Audio) is enabled, other speakers volumes reduce to what feels like 25% *
1. There is no change of volume when players walk around (up to 100s of m away)

## Changing all variables

![image](https://github.com/alifeee/Factorio-Proximity-Voice-Chat/assets/13833017/5eabed9f-b752-4586-8ce4-29abf5c555ff)

1. [The same as above.]

## Conclusion

It feels like:

1. PA is enabled, because of the volume drop on enabling/disabling it.
1. The "Minimum Volume" setting above has no effect, and that the Postional Audio has no effect.

This could be an issue with

- Postional Audio in Mumble v1.5
- The direction/axis should be set to something
  - These may be required to be unit vectors(?)

## Next steps:

- [x] try an existing plugin (Among Us/L4D2)
- [x] try with direction/axis vectors set
- [x] try with Mumble 1.4
- [x] if those do not work, further action is unknown

**Comment by alifeee** [comment]
It works! 

## Mumble 1.4

With these settings

![image](https://github.com/alifeee/Factorio-Proximity-Voice-Chat/assets/13833017/a2e49a1c-e936-4ff4-90da-3858032a8239)

it works! 1 chest in game (1 square) is 1 metre in Mumble.

## Mumble 1.5

Doesn't seem to fully work, for example:

> when using the above settings, I could hear another player at any distance away. They stopped hearing me as usual. Increasing/decreasing minimum volume had the intended effect, but it never went fully to 0%.

**Comment by Hartmnt** [comment]
mumble-voip/mumble#6149

**Comment by alifeee** [comment]
It works in Mumble 1.4

It does not work in Mumble 1.5 (until https://github.com/mumble-voip/mumble/issues/6149 is fixed)

**Comment by Hartmnt** [comment]
The positional audio fixes have been merged into master an will most likely land in the next 1.5 RC

**Comment by alifeee** [comment]
> The positional audio fixes have been merged into master an will most likely land in the next 1.5 RC

beautiful :)
